# Generated by Django 4.0 on 2022-03-03 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('userpassword', models.CharField(max_length=30)),
                ('usertype', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('profilePic', models.ImageField(upload_to='')),
                ('jobtype', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('subcategory', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('additional_information', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('place', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('education_qualification', models.CharField(max_length=30)),
                ('workerlogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('profilePic', models.ImageField(upload_to='')),
                ('pincode', models.IntegerField()),
                ('address', models.TextField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('star', models.CharField(max_length=30)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Quick_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('landmark', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Package_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=30)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.login')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.workerdetails')),
            ],
        ),
    ]
