# Generated by Django 4.0 on 2022-03-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_booking_city_remove_quick_booking_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='status',
        ),
    ]
