# Generated by Django 4.0 on 2022-03-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_login_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
